name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Fly.io CLI
        run: |
          curl -fsSL https://fly.io/install.sh | sh
          export PATH=$HOME/.fly/bin:$PATH

      - name: Deploy to Fly.io
        run: fly deploy -a flowisexvmkeq
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
